version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: mysql-database
    container_name: mysql-database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: passwordRoot
    networks:
      network-database:
        ipv4_address: 173.20.0.4
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-interface
    ports:
    - 8083:80
    depends_on:
      - db
    networks:
      network-database:
        ipv4_address: 173.20.0.5

networks:
  network-database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.20.0.0/24