version: "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./postgres/bk:/bk"
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      net_postgres:
        ipv4_address: 172.16.18.2

  pgAdmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.postgres.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8080:80
    networks:
      net_postgres:
        ipv4_address: 172.16.18.3

networks:
  net_postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.18.0/24
